-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE m
WHERE DATE_FORMAT(m.DATE_OF_BIRTH,'%Y-%m-%d') LIKE '%-03-%' AND m.TLNO IS NOT NULL and m.GENDER='w'
ORDER BY m.MEMBER_ID ASC;