-- 코드를 입력하세요
SELECT a.CATEGORY, SUM(b.SALES) AS TOTAL_SALES
FROM BOOK a INNER JOIN BOOK_SALES b ON a.BOOK_ID = b.BOOK_ID
WHERE b.SALES_DATE LIKE '2022-01-%'
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY ASC